echo "apt"
cowsay -f apt "hello world"
echo "elephant"
cowsay -f elephant "hello world"
echo "luke-koala"
cowsay -f luke-koala "hello world"
echo "stimpy"
cowsay -f stimpy "hello world"
echo "bud-frogs"
cowsay -f bud-frogs "hello world"
echo "elephant-in-snake"
cowsay -f elephant-in-snake "hello world"
echo "mech-and-cow"
cowsay -f mech-and-cow "hello world"
echo "suse"
cowsay -f suse "hello world"
echo "bunny"
cowsay -f bunny "hello world"
echo "eyes"
cowsay -f eyes "hello world"
echo "milk"
cowsay -f milk "hello world"
echo "three-eyes"
cowsay -f three-eyes "hello world"
echo "calvin"
cowsay -f calvin "hello world"
echo "flaming-sheep"
cowsay -f flaming-sheep "hello world"
echo "moofasa"
cowsay -f moofasa "hello world"
echo "turkey"
cowsay -f turkey "hello world"
echo "cheese"
cowsay -f cheese "hello world"
echo "fox"
cowsay -f fox "hello world"
echo "moose"
cowsay -f moose "hello world"
echo "turtle"
cowsay -f turtle "hello world"
echo "cock"
cowsay -f cock "hello world"
echo "ghostbusters"
cowsay -f ghostbusters "hello world"
echo "pony"
cowsay -f pony "hello world"
echo "tux"
cowsay -f tux "hello world"
echo "cower"
cowsay -f cower "hello world"
echo "gnu"
cowsay -f gnu "hello world"
echo "pony-smaller"
cowsay -f pony-smaller "hello world"
echo "unipony"
cowsay -f unipony "hello world"
echo "daemon"
cowsay -f daemon "hello world"
echo "hellokitty"
cowsay -f hellokitty "hello world"
echo "ren"
cowsay -f ren "hello world"
echo "unipony-smaller"
cowsay -f unipony-smaller "hello world"
echo "default"
cowsay -f default "hello world"
echo "kangaroo"
cowsay -f kangaroo "hello world"
echo "sheep"
cowsay -f sheep "hello world"
echo "vader"
cowsay -f vader "hello world"
echo "dragon"
cowsay -f dragon "hello world"
echo "kiss"
cowsay -f kiss "hello world"
echo "skeleton"
cowsay -f skeleton "hello world"
echo "vader-koala"
cowsay -f vader-koala "hello world"
echo "dragon-and-cow"
cowsay -f dragon-and-cow "hello world"
echo "koala"
cowsay -f koala "hello world"
echo "snowman"
cowsay -f snowman "hello world"
echo "www"
cowsay -f www "hello world"
echo "duck"
cowsay -f duck "hello world"
echo "kosh"
cowsay -f kosh "hello world"
echo "stegosaurus"
cowsay -f stegosaurus "hello world"
